### ISSUE TITLE
Небезопасный каст

### ISSUE THREAD

**Issue by VitalyNikonorov** [Ishokov-Dzhafar/Notes#1]
https://github.com/Ishokov-Dzhafar/Notes/blob/3548e7ccc3932db44601bdeb34bf05478a039d9e/app/src/main/java/kot/notes/notes/data/entity/SortNoteByDate.kt#L9

**Comment by Ishokov-Dzhafar** [comment]
Почему?

**Comment by Ishokov-Dzhafar** [comment]
Почему это не безопасный каст?
